Add bots api v4 support
ExpressApp/pybotx pull request #100
Opened 2020-12-01 11:03 UTC by Opti213

### Add

* Support of reply in messages for bot's api v4
* Entity building methods for `MessageBuilder` 
* Flag `is_forward` for `Message`
* Bot's method `reply` 

### Changed

* `message.entities` now is `EntityList`(like `AttachList`) not `List[Attachment]`

2020-12-01 15:20 UTC, lxmnk commented on botx/bots/mixins/requests/events.py
> +        if not text and not file:
```python
if not (text or file):
```

2020-12-01 15:47 UTC, lxmnk approved these changes

2020-12-02 05:46 UTC, nsidnev requested changes

2020-12-02 05:46 UTC, nsidnev commented on docs/changelog.md
> +## 0.16.0 (Nov 30, 2020)
synchronize release dates with PyPI

2020-12-02 05:46 UTC, nsidnev commented on docs/changelog.md
> +### Add
look at right format: https://keepachangelog.com/en/1.0.0/

2020-12-04 08:09 UTC, nsidnev approved these changes

2020-12-07 05:36 UTC, merged