Add `chat_info` bot method
ExpressApp/pybotx pull request #224
Opened 2021-11-09 11:39 UTC by YunusovSamat

# Description

Please include a summary of the change.

# Checklist

- [ ] Linters and tests have passed
- [ ] I've written a changelog for PR change
- [ ] I'll make a release when PR is approved

2021-11-09 14:10 UTC, lxmnk commented on .gitignore
> +
Empty line.

2021-11-09 14:29 UTC, lxmnk requested changes

2021-11-09 14:29 UTC, lxmnk commented on botx/client/chats_api/chat_info.py
> +    server_id: UUID
This field does not provide useful information. Remove it, pls.

2021-11-09 14:29 UTC, lxmnk commented on botx/client/chats_api/chat_info.py
> +    inserted_at: dt
`created_at`

2021-11-09 14:29 UTC, lxmnk commented on botx/client/chats_api/chat_info.py
> +    creator: UUID
`creator_id`

2021-11-09 14:29 UTC, lxmnk commented on botx/client/chats_api/chat_info.py
> +    user_kind: BotAPIUserKinds
Pls move this enum to shared models.

2021-11-09 14:29 UTC, lxmnk commented on botx/client/chats_api/chat_info.py
> +    server_id: UUID
Remove.

2021-11-10 08:18 UTC, lxmnk approved these changes

2021-11-10 12:01 UTC, Nimond approved these changes

2021-11-10 14:22 UTC, merged